baseURL = "https://example.org/"
languageCode = "en-us"
title = "tw-hugo"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 2
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3

[params]
  description = "This is the description for the website."

[permalinks]
  blog = "/:filename/"
  page = "/:filename/"
