backend:
    name: git-gateway
    branch: master

collections:
    -   name: "blog" # Used in routes, e.g., /admin/collections/blog
        label: "Blog"
        folder: "content/blog"
        create: true
        fields: # https://www.netlifycms.org/docs/widgets/
            - {label: "Title", name: "title", widget: "string"}
            - {label: "Categories", name: "categories", widget: "list", required: false}
            - {label: "Cover", name: "cover", widget: "image"}
            - {label: "Date", name: "date", widget: "datetime"}
            - {label: "Featured", name: "featured", widget: "boolean", default: false}
            - {label: "Summary", name: "summary", widget: "string"}
            - {label: "Tags", name: "tags", widget: "list", required: false}
            - {label: "Draft", name: "draft", widget: "boolean", default: true}
            - {label: "Body", name: "body", widget: "markdown"}

media_folder: "static/img/uploads" # Media files will be stored in the repo under static/img/uploads
public_folder: "/img/uploads" # The src attribute for uploaded media will begin with /img/uploads
